name: "Hello world"
description: "Greet someone in docker"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time:
    description: "The time you were greeted"
runs:
  using: "docker"
  image:  Dockerfile
  args:
    - ${{ inputs.who-to-greet }}

